name: Laravel_Test_And_Deploy

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: add permission
      run: chmod -R g+w api && sudo groupadd -f daemon && sudo chown -R :daemon api
    - name: ssh key generate
      run: echo "$SSH_PRIVATE_KEY" ＞ key && chmod 600 key
      env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: rsync deploy
      run: rsync -rptgDvz --delete --exclude-from=./.rsyncignore -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./ bitnami@13.231.31.143:/home/bitnami/htdocs/laravel/
    - name: migrate database
      run: ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no bitnami@13.231.31.143 'cd /home/bitnami/htdocs/laravel/ && php artisan migrate'      
